name: Test Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Restore node_modules
        uses: actions/cache@v2
        id: restore-node-modules
        env:
          cache-name: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Restore Yarn cache
        uses: actions/cache@v2
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        env:
          cache-name: yarn-cache
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Run Test with Coverage
        run: yarn test:coverage
